# Generated by Django 4.2.7 on 2024-01-25 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_alter_post_author_alter_post_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coment', '0004_alter_commentarytoauthor_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarytoauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='commentarytoauthor',
            name='to_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='announcement.post', to_field='title', verbose_name='На публикацию'),
        ),
    ]
