# Generated by Django 4.2.7 on 2023-12-08 19:07

import announcement.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=announcement.services.post_media_directory_path, verbose_name='Файлы медиа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=announcement.services.post_media_directory_path, verbose_name='Картинки'),
        ),
    ]
