# Generated by Django 4.2.7 on 2024-02-11 10:50

import announcement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=announcement.models.post_media_directory_path, verbose_name='Файлы медиа'),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=announcement.models.post_media_directory_path, verbose_name='Картинки'),
        ),
    ]
