# Generated by Django 4.2.7 on 2024-02-19 09:10

import cabinet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=cabinet.models.post_media_directory_path, verbose_name='Фотография'),
        ),
    ]
